# Generated by Django 4.1.7 on 2023-02-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='teacher.subject'),
        ),
    ]
